In [5]:
from sklearn.datasets import load_iris
data = load_iris()
data.target[[10, 25, 50]]

array([0, 0, 1])

In [11]:
#Ejercicio 1

#importamos en numpy como np
import numpy as np
from sklearn.datasets import load_iris

#cargamos el conjunto de datos
iris = load_iris()

# Accedemos a los datos de las flores y a las etiquetas de las especies.
data = iris.data
target = iris.target

#Convertimos los datos en Array de numpy. 
data_np = np.array(data)
target_np = np.array(target)

# Visualizamos los 10 pirmeros registros de data (iris.data) y target (iris.target)
print("Primeros 10 registros de los datos:")
print(data_np[:10, :])

print("\nPrimeros 10 registros de las etiquetas:")
print(target_np[:10])




Primeros 10 registros de los datos:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]

Primeros 10 registros de las etiquetas:
[0 0 0 0 0 0 0 0 0 0]


In [15]:
#Ejercicio 2

#Aqui nos saltamos la primera parte de cargar los datos, ya que lo hemos cargado en el ejercicio anterior
#y no es necesario volver hacerlo.

#concatenamos la data y target en un nuevo Array.

# Concatena "data" i "target" en un nou array. Usamos np.concatenate para unificar las caracteristicas.
concatenated_array = np.concatenate((data_np, target_np.reshape(-1, 1)), axis=1)

# Visualizamos los 5 primeros registros del nuevo array
print("5 primeros registros del nuevo array:")
print(concatenated_array[:5, :])


5 primeros registros del nuevo array:
[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


In [20]:
#Ejercicio 3
#Cogemos solo la parte de data, ya qya la otra no nos interesa en este ejercicio.

# Convertimos los datos en Array de numpy. 
data_np = np.array(data)

# Calculamos la media y la desv.standard de la longitud del sepal y petal.
sepal_length_mean = np.mean(data_np[:, 0])
sepal_length_std = np.std(data_np[:, 0])

petal_length_mean = np.mean(data_np[:, 2])
petal_length_std = np.std(data_np[:, 2])

# Mmostramos los resultados con 2 decimales.
print("Media de la longitud del sépal es: {:.2f}".format(sepal_length_mean))
print("D.standard de la longitud del sépal es: {:.2f}".format(sepal_length_std))
print("\Media de la longitud del pètal es: {:.2f}".format(petal_length_mean))
print("Desv.standard de la longitud dell pètal es: {:.2f}".format(petal_length_std))


Media de la longitud del sépal es: 5.84
D.standard de la longitud del sépal es: 0.83
\Media de la longitud del pètal es: 3.76
Desv.standard de la longitud dell pètal es: 1.76


In [23]:
#Ejercicio 4

# Concatenamos para combinar las caracteristicas y las etiquetas, como hicimos en el ejercicio2.
concatenated_array = np.concatenate((data_np, target_np.reshape(-1, 1)), axis=1)

# Selecciona uuna muestra aleatorio de 20 registros. Aquí usamos Np.random.choice para seleccionar los 20indices
#sin reemplazo de los registros disponibles.
random_sample_indices = np.random.choice(concatenated_array.shape[0], size=20, replace=False)
random_sample = concatenated_array[random_sample_indices, :]

# Mostra la mostra aleatòria
print("Muestra aleatorio de 20 registros:")
print(random_sample)


Muestra aleatorio de 20 registros:
[[5.2 3.4 1.4 0.2 0. ]
 [6.8 3.2 5.9 2.3 2. ]
 [6.1 3.  4.6 1.4 1. ]
 [4.8 3.4 1.6 0.2 0. ]
 [5.7 2.8 4.5 1.3 1. ]
 [4.7 3.2 1.3 0.2 0. ]
 [7.3 2.9 6.3 1.8 2. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.9 3.  5.1 1.8 2. ]
 [4.6 3.1 1.5 0.2 0. ]
 [6.3 2.3 4.4 1.3 1. ]
 [6.7 2.5 5.8 1.8 2. ]
 [5.  3.5 1.6 0.6 0. ]
 [6.9 3.1 5.4 2.1 2. ]
 [6.6 3.  4.4 1.4 1. ]
 [4.9 3.6 1.4 0.1 0. ]
 [6.2 2.2 4.5 1.5 1. ]
 [4.9 3.  1.4 0.2 0. ]
 [5.9 3.2 4.8 1.8 1. ]
 [5.  2.3 3.3 1.  1. ]]


In [29]:
#Ejercicio 5

# Convertimos los datos en Array de numpy. 
data_np = np.array(data)

# Volvemos a concatenar como ejercicios anteriores. 
concatenated_array = np.concatenate((data_np, target.reshape(-1, 1)), axis=1)

# Creamos una matrizar para guardar la media y la desv.standard por especie.
# la matriz tiene 3filas (especies) 5 columnas(4 para las carecterosticas y 1 para la etiqueta de la especie) 
resultado_matrix = np.zeros((3, data.shape[1] + 1))  #la  3 espècies, 4 característiques + 1 columna per a l'etiqueta

# Iteramos para cada especie. Iniciamos un bucle que itera sobre cada especie, en el conjunto de datos hay 3 especies. 
for i in range(3):
    # Filtramos los datos por especie.
    species_data = concatenated_array[concatenated_array[:, -1] == i, :-1]
    
    # Calculamos la media y la desv.standard pro especie
    mean_values = np.mean(species_data, axis=0)
    std_values = np.std(species_data, axis=0)
    
    #guardamos los resultados en la matrix
    result_matrix[i, :-1] = mean_values
    result_matrix[i, -1] = i  

# Mostramos los resultados con 2 decimales.
np.set_printoptions(precision=2)
print("Media y desv.standard de cada característica por especie:")
print(resultado_matrix)


Media y desv.standard de cada característica por especie:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [34]:
#Ejercicio 6

# Calculamos la cantidad de muestras por especie.
samples_por_especies = np.bincount(concatenated_array[:, -1].astype(int))

# Buscamos la especia con el valor máximo de la media de "sepal length (cm)"
mean_sepal_length_por_especies = np.zeros(3)

# Itera per cada espècie
for i in range(3):
    # Filtramos los datos por especie.
    especies_data = concatenated_array[concatenated_array[:, -1] == i, :]
    
    # Calculamos la media de "sepal length (cm)" por especie
    mean_sepal_length_por_especies[i] = np.mean(especies_data[:, 0])

# Indice de la especie con la media maxima
max_mean_especies_index = np.argmax(mean_sepal_length_por_especies)

# Mostramos los resultados
print("Cantidad de muestras por especie:")
for i in range(3):
    print(f"Especie {i}: {samples_per_species[i]} muestras")

print("\nEspecie con el valor máximo de la media de 'sepal length (cm)':")
print(f"Especie {max_mean_species_index} con media de {mean_sepal_length_por_especies[max_mean_species_index]:.2f}")


Cantidad de muestras por especie:
Especie 0: 50 muestras
Especie 1: 50 muestras
Especie 2: 50 muestras

Especie con el valor máximo de la media de 'sepal length (cm)':
Especie 2 con media de 6.59


In [38]:
#Ejercicio 7


# Accedemos a los datos 
data = iris.data
feature_names = iris.feature_names

# Convertimos los datos en un DataFrame de Pandas
df = pd.DataFrame(data, columns=feature_names)

# Calculamos la matriz de correlación entre las variables
correlation_matrix = df.corr()

# Mostramos la matriz de correlación
print("Matriz de correlación entre las variables:")
print(correlation_matrix)

# Filtramos los valores mayores a la media de la longitud de petalos
mean_petal_length = df['petal length (cm)'].mean()
filtered_values = df[df['petal length (cm)'] > mean_petal_length]

# Valores filtradose
print("\nValores mayores a la media de la longitud de los pètals:")
print(filtered_values)

# Buscamos la muestra con los petalos más grandes
max_petal_length_index = df['petal length (cm)'].idxmax()
sample_with_max_petals = df.loc[max_petal_length_index]

# La muestra con los petalos más grandes
print("\nMuestra con los petalos más grandes:")
print(sample_with_max_petals)


Matriz de correlación entre las variables:
                   sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)          0.817941  
sepal width (cm)          -0.366126  
petal length (cm)          0.962865  
petal width (cm)           1.000000  

Valores mayores a la media de la longitud de los pètals:
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
50                 7.0               3.2                4.7               1.4
51                 6.4               3.2                4.5               1.5
52                 6.9               3.1                4.9               1.5
53         

In [39]:
#Ejercicio 8

#Importamos la librería numpy para operaciones numericas y luego la de pandas para manipular y analizar los datos
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

# Cargamos el cconjunto de datos
iris = load_iris()

# Accedemos a los datos: caracteristicas, nombres de caracteristicas y nombres de especies
data = iris.data
feature_names = iris.feature_names
target_names = iris.target_names

# Creamos un dataframe de pandas y agregamos una columna llamada "species"
df = pd.DataFrame(data, columns=feature_names)
df['species'] = target_names[iris.target]

# Calculo de la media de la longitud de los sepals y pètals por especie
mean_sepal_length = df.groupby('species')['sepal length (cm)'].mean()
mean_petal_length = df.groupby('species')['petal length (cm)'].mean()

# Calculamos la diferencia entre las medias
difference = np.abs(mean_sepal_length - mean_petal_length)

# BUscamos la especie con la diferencia mas grande
max_difference_species = difference.idxmax()

# Resultados
print("Especie con la diferencia más grande entre la longitud de la media de sèpals y pètals:")
print(max_difference_species)


Especie con la diferencia más grande entre la longitud de la media de sèpals y pètals:
setosa
